Fix code scanning alert no. 2: Too few arguments to formatting function
Error: Too few arguments to formatting function HAP_debug_v2
Fix: add the missing argument to the FARF call on line 212. The missing argument should be the return value ret

Signed-off-by: Tharun Kumar Merugu <quic_mtharu@quicinc.com>